In [2]:
! pip install numpy tensorflow scikit-learn

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 585.9/585.9 MB 1.9 MB/s eta 0:00:0000:0100:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 126.5/126.5 kB 7.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.5/57.5 kB 3.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.1/5.1 MB 47.2 MB/s eta 0:00:00:00:0100:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.6/4.6 MB 35.9 MB/s eta 0:00:0000:0100:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 33.4 MB/s eta 0:00:00:00:01
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 30.5 MB/s eta 0:00:0000:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 22.9/22.9 MB 44.6 MB/s eta 0:00:0000:0100:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 17.1/17.1 MB 50.7 MB/s eta 0:00:0000:0100:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 65.5/65.5 kB 3.8 MB/s eta 0:00:00
   

# Bắt đầu

In [2]:
import tensorflow as tf
import numpy as np
import sklearn
print(np.__version__)
print(tf.__version__)
print(sklearn.__version__)

2023-05-31 08:02:46.841658: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-05-31 08:02:49.306266: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-05-31 08:02:49.321182: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-05-31 08:02:54.110827: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT


1.23.5
2.12.0
1.2.2


## CÁCH TẠO:
* 1 scalar kích thước 1
* 1 vector kích thước 2
* 1 matrix (Ma trận) kích thước 2 x 2
* 1 tensor kích thước 2 x 2 x 2
## GIẢI THÍCH:
### * VỀ SCALAR,VECTOR,MATRIX
* Scarlar : Chứa một số duy nhất
* Vector : Chứa số với 1 chiều duy nhất (Ví dụ:Tốc độ của gió và chiều.)
* Matrix : Chứa số với 2 chiều (Ví dụ: Bản đồ khu phố)
* Tensor : Chứa số với n chiều (n Ở đây có nghĩa là không giới hạn chiều ; Ví dụ: Thùng chứa trong nhà kho của nhà xưởng sản xuất sữa)
### * VỀ HÀM ```tf.constant()```
* Hàm ```tf.constant()``` trông như thế này:
* <code>tf.constant(value, dtype=None, shape=None, name='Const')</code>
* Nó tác dụng tạo ra một mảng theo value,dtype,shape,name đã cho.
* Có thể xem thêm tài liệu tại trang tensorflow bằng cách click [vào đây.](https://www.tensorflow.org/api_docs/python/tf/constant)
### * VỀ HÀM ```.ndim```
* Hàm ```.ndim``` trông như thế này: 
* <code>bien_bat_ki.ndim</code>
* Nó tác dụng trả về số chiều của biến đã cho.

In [6]:
#Một scalar
scalar = tf.constant([10])
print(scalar)
print(scalar.ndim)
#Một vector
vector = tf.constant([10,10])
print(vector)
print(vector.ndim)
#Một ma trận
matrix = tf.constant([[10,10],[10,10]])
print(matrix)
print(matrix.ndim)
#Một tensor
tensor = tf.constant([[[10,10],[10,10]],[[10,10],[10,10]]])
print(tensor)
print(tensor.ndim)

tf.Tensor([10], shape=(1,), dtype=int32)
1
tf.Tensor([10 10], shape=(2,), dtype=int32)
1
tf.Tensor(
[[10 10]
 [10 10]], shape=(2, 2), dtype=int32)
2
tf.Tensor(
[[[10 10]
  [10 10]]

 [[10 10]
  [10 10]]], shape=(2, 2, 2), dtype=int32)
3
